### ISSUE TITLE
Issue with roles for different Model types

### ISSUE THREAD

**Issue by travega** [SimplyBuilt/SimonSays#4]
I have a Devise User model with 3 subtypes "Player", "Hero" and "Coach". Each of the subtypes have their own set of roles. However, I only seem to be able to add one set of roles to a user. If I try to add a different set of roles to a different user type the roles mask is 0 with an empty roles array.

Simplified example:

```ruby
class User < ApplicationRecord
  before_create :add_roles

  include SimonSays::Roleable
  has_roles  :content_creator, :story_admin, :advertiser, :promoter, :team_admin

  private

  def add_roles
    case self.type
      when 'Player'
        self.roles = %i[content_creator story_admin]
      when 'Hero'
        self.roles = %i[content_creator story_admin]
      when 'Coach'
        self.roles = %i[promoter team_admin]
    end
  end
end
```

Outcome:

```ruby
Player.create!({params})
Player.first.roles
# [:content_creator, :story_admin]

Hero.create!({params})
Hero.first.roles
# [:content_creator, :story_admin]

Coach.create!({params})
Coach.first.roles
# []
```

Every time I try to add a different set of roles to a User type the roles array comes up empty. Any advice on how to solve this issue?

**Comment by mikeycgto** [comment]
Are the models valid? If validation is failing the `before_create` will not run and thus no roles will be set. Maybe try using a `before_validation` callback instead.
