### ISSUE TITLE
1.0 Release Schedule 

### ISSUE THREAD

**Issue by SeanDunford** [SimplyBuilt/SimonSays#7]
Hi, I work at [@knotchlabs](https://github.com/KnotchLabs)  my company uses this gem in production. We love it and respect your work but I'd like to see it come out of Alpha. 

Is there a 1.0 release schedule available? If you need help one of our core engineers @mjc-gh has plenty of free cycles and he would be more than happy to jump in and help.

**Comment by JNKHunter** [comment]
Hey Sean, thanks for your kind words. @mjc-gh (a VP at your company) is already regular committer to this repo. He's also the person who originally created the gem. Mike has earned the right to call it alpha, beta, gamma, Shirley, or whatever his heart desires.
